version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
    groups:
      codeql-actions:
        patterns:
          - "github/codeql-action*"
      codeql-security-actions:
        applies-to: security-updates
        patterns:
          - "github/codeql-action*"
